# Generated by Django 5.2.6 on 2025-09-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pglisting',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated list of amenities', null=True),
        ),
        migrations.AddField(
            model_name='pglisting',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pglisting',
            name='type_of_pg',
            field=models.CharField(blank=True, choices=[('boys', 'Boys'), ('girls', 'Girls'), ('coed', 'Coed'), ('family', 'Family')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='sharing_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quad', 'Quad')], max_length=20),
        ),
    ]
