# Generated by Django 5.2.6 on 2025-09-18 14:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgs', '0002_pglisting_amenities_pglisting_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pglisting',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
